### ISSUE TITLE
icons looking not as intended

### ISSUE THREAD

**Issue by Karyum** [FACN8/PetHub#21]
not sure why but on my computer, the icons look like this 
![Screenshot from 2020-02-27 12-07-04](https://user-images.githubusercontent.com/24195641/75434149-ccbb2680-5959-11ea-9f31-f1c3a9384120.png)

**Comment by LogicX1** [comment]
We used emojis, and each system/browser renders them differently, we can't change that but if we have time we can swap them to local images
