### ISSUE TITLE
optimize ternary operators in app.js

### ISSUE THREAD

**Issue by Karyum** [FACN8/PetHub#22]
https://github.com/FACN8/PetHub/blob/master/src/App.js#L14-L18

instead of writing the conditions likes `localStorage.getItem('health') ? localStorage.getItem('health') : 100`

you could do `localStorage.getItem('health') || 100` the `||` operator will take the first one that is truthy

**Comment by LogicX1** [comment]
Thanks for the suggestion, I changed them
