### ISSUE TITLE
CSS file structure optimizations 

### ISSUE THREAD

**Issue by Karyum** [FACN8/PetHub#24]
you have some nicely named classes, but later on if you are working on a big project you can't have all css in just 1 file.

there multiple ways of going about this, and you don't need to do this but what i would suggest is that every component has it's own folder, the folder name would be the component name and it has an `index.js` or `index.jsx` and the CSS file which holds the component's own CSS

**Comment by LogicX1** [comment]
We had separate css files but the then we moved everything into one file because its a small project and the team disliked the idea of having so many files that don't have much in them
